### ISSUE TITLE
Feature Request: Specify single digits like in vim-vertigo

### ISSUE THREAD

**Issue by RealFerdinandDeSaussure** [noctuid/vertigo.el#2]
First off, thanks for this package. I use it all the time and think that by providing `vertigo-set-digit-argument` it's actually superior to vim-vertigo. That being said, it would be really great if vertigo.el could provide an alternate way of differentiating between single-digit and double-digt arguments. I think the vim-vertigo way of using uppercase for single and lower case for dual digit arguments is pretty smart. This could also be implemented by exposing a setting to bind both kind of arguments to different keys.
I agree that jumping up and down with the vertigo keys doesn't make much sense when it's just for two or three lines. But I use `vertigo-seti-digit-argument` for eeeeeverything and sometimes it does make sense to provide very low or very large counts as arguments.

**Comment by noctuid** [comment]
I've implemented your suggestion but only had time to test it briefly (I don't regularly use this package anymore). Please try it out and let me know if you encounter any issues.

**Comment by RealFerdinandDeSaussure** [comment]
Works beautfiully from what I can tell. Thank you so much for implementing this right away!
