### ISSUE TITLE
`vertigo-jump-down` does not work consistently

### ISSUE THREAD

**Issue by alienbogart** [noctuid/vertigo.el#3]
**Environment**:

- OS: MX Linux 17
- i3 version 4.13 (2016-11-08)
- GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.31) of 2018-08-16
- Evil version 1.2.13
- [.emacs.d](https://gitlab.com/mrbig/emacs)

**Issue**

When I input a letter in `vertigo-jump-down` or `vertigo-jump-up` corresponding to a line that is not visible, it exits without performing the motion.

**Example**:

On the start of a 200 lines `*.vim` file with only 40 visible lines, I call `vertigo-jump-down` and type `gs` to go 52 lines down. Vertigo takes the first input, but on the second it exits and I end up performing the `evil-substitute` command.

The same happens if I'm on the end of the file and use `vertigo-jump-up`.

**Comment by noctuid** [comment]
The expected/default behavior when you type `g` is for the point to move down 5 lines. Have you customized `vertigo-cut-off` or `vertigo-max-digits`?

**Comment by alienbogart** [comment]
I haven't made [any customization](https://gitlab.com/mrbig/emacs/blob/master/init.el#L121) other than the [keybindings to call Vertigo](https://gitlab.com/mrbig/emacs/blob/master/init.el#L555).

**Comment by alienbogart** [comment]
Okay, maybe there was come config before. Right now, the `g` key goes down 5 lines. But what would I have to do to go 50 lines down?

**Comment by noctuid** [comment]
You will either need to increase the cutoff to more than 5 or change the max digits if you want to be able to jump 100 or more lines.

**Comment by alienbogart** [comment]
Okay, that worked. Thanks! Just a suggestion: since the Vim version defaults to a two-digit, 99 lines cut off, why make not make it the same in the Emacs version?
